from fpdf import FPDF
import io
from datetime import datetime

class ReportPDF(FPDF):
    def header(self):
        # We don't have a logo file readily available, so we'll just stylize the text header
        self.set_font("helvetica", "B", 20)
        self.set_text_color(40, 50, 60)
        self.cell(0, 10, "SafeWatch AI", border=False, align="C", new_x="LMARGIN", new_y="NEXT")
        
        self.set_font("helvetica", "I", 12)
        self.set_text_color(100, 110, 120)
        self.cell(0, 10, "Adverse Event Report Validation", border=False, align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}} | Automatically generated by SafeWatch AI", align="C")

def generate_report_pdf(report):
    """
    Takes an SQLAlchemy Report model instance and returns a PDF byte buffer.
    """
    pdf = ReportPDF()
    pdf.add_page()
    pdf.set_font("helvetica", size=12)

    # Document Title / Metadata
    pdf.set_font("helvetica", "B", 16)
    pdf.set_text_color(20, 30, 40)
    pdf.cell(0, 10, f"Report Reference #{report.id}", new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font("helvetica", "", 10)
    pdf.set_text_color(80, 80, 80)
    
    # Format the timestamp nicely
    try:
        dt = datetime.fromisoformat(report.timestamp)
        formatted_time = dt.strftime("%B %d, %Y at %I:%M %p")
    except ValueError:
        formatted_time = report.timestamp
        
    pdf.cell(0, 8, f"Submitted on: {formatted_time}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 8, f"Status: Logged", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(10)

    # Patient Section
    pdf.set_font("helvetica", "B", 14)
    pdf.set_fill_color(240, 245, 250)
    pdf.cell(0, 10, " Patient Demographics", border=True, fill=True, new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font("helvetica", "", 12)
    pdf.cell(40, 10, "Age:", border=False)
    pdf.cell(0, 10, report.age if report.age else "Unknown", new_x="LMARGIN", new_y="NEXT")
    
    pdf.cell(40, 10, "Gender:", border=False)
    pdf.cell(0, 10, report.gender if report.gender else "Unknown", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # Reaction Section
    pdf.set_font("helvetica", "B", 14)
    pdf.set_fill_color(255, 240, 240)
    pdf.cell(0, 10, " Adverse Event Details", border=True, fill=True, new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font("helvetica", "", 12)
    pdf.cell(40, 10, "Suspect Drug:", border=False)
    pdf.set_font("helvetica", "B", 12)
    pdf.cell(0, 10, str(report.drug).capitalize(), new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font("helvetica", "", 12)
    pdf.cell(40, 10, "Reaction(s):", border=False)
    pdf.multi_cell(0, 10, str(report.reaction))
    pdf.ln(15)

    # Disclaimer
    pdf.set_font("helvetica", "I", 9)
    pdf.set_text_color(150, 150, 150)
    disclaimer = (
        "Disclaimer: This report was generated contextually by SafeWatch AI based on user input. "
        "It is not a verified medical document. Please consult a healthcare professional "
        "if you are experiencing a severe adverse reaction."
    )
    pdf.multi_cell(0, 6, disclaimer, align="J")

    # Output to BytesIO buffer
    pdf_buffer = io.BytesIO()
    pdf.output(pdf_buffer)
    pdf_buffer.seek(0)
    
    return pdf_buffer
